-- 코드를 입력하세요
SELECT RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS, round(avg(RR.REVIEW_SCORE), 2) SCORE
from REST_REVIEW RR
join REST_INFO RI on (RR.REST_ID = RI.REST_ID)
where RI.ADDRESS like '서울%'
group by RR.REST_ID
order by SCORE DESC, RI.FAVORITES DESC