-- 코드를 입력하세요
SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') PUBLISHED_DATE
from BOOK B
join AUTHOR A on (B.AUTHOR_ID = A.AUTHOR_ID)
where B.CATEGORY = '경제'
order by PUBLISHED_DATE